### ISSUE TITLE
Paragraph Indentation Carpet Bombing

### ISSUE THREAD

**Issue by grayghostvisuals** [typeplate/typeplate.github.io#119]
Our current method to style paragraphs is a PAIN IN THE ASS and I'm tired of it carpet bombing everything. We need a more robust way to handle this. Anybody have thoughts on this?

``` scss
//paragraph siblings indent
$indent-val: 1.5em !default;

p {
    margin: auto auto $indent-val;
    & + p {
        text-indent: $indent-val;
        margin-top: -$indent-val;
    }
}
```
