### ISSUE TITLE
Make word-wrap and break-word a boolean

### ISSUE THREAD

**Issue by grayghostvisuals** [typeplate/typeplate.github.io#121]
So I've had three projects where each client and the company designers hated the word wrap hyphenation we're currently using.

We need this placed into a variable that is a boolean of some sort. Probably should do it for the break-word property as well.

``` scss
body {
    // Ala Trent Walton
    @include css-hyphens(auto);

    // normal: Indicates that lines may only break at normal word break points.
    // break-word : Indicates that normally unbreakable words may be broken at ...
    // arbitrary points if there are no otherwise acceptable break points in the line.
    @extend %breakword;
    color: $body-copy-color;
}
```
