### ISSUE TITLE
Block Quote update with figure and figcaption

### ISSUE THREAD

**Issue by jhogue** [typeplate/typeplate.github.io#95]
The standard for `blockquote` should be upgraded, mostly because `blockquote` is very strict about what it allows inside. A complete `blockquote` with a `cite` really should include `figure` and `figcaption`. [The research and reasoning is explained here](http://www.projectevolution.com/activity/how-do-you-solve-a-problem-like-blockquote/). 

Here is the proposed markup: 

``` html
<figure>
    <blockquote cite="//dev.w3.org/html5/spec/grouping-content.html#the-blockquote-element">
        <p>The blockquote element represents a section that is quoted from another source.</p>
    </blockquote>
    <figcaption>— <cite><a href="http://dev.w3.org/html5/spec/grouping-content.html#the-blockquote-element" title="4.5 Grouping content — HTML5">W3C HTML5 specification</a></cite></figcaption>
</figure>
```

Which would more easily allow a positioned open curly quote and an inline closing curly quote, as this style indicates: 

``` css
blockquote {
    font: italic 1.125em Georgia, serif; 
    line-height: 1.75; 
    padding: .5em 1.5em 0;
    position: relative;

    &:before, p:last-child:after {
        font-style: normal; 
        font-weight: 700; 
        font-size: 2.25em;
    }
    &:before {
        content: "“";
        position: absolute;
        top: -0.0625em; left: 0;
    }
    p:last-child:after {
        display: inline; 
        content: "”";
        line-height: 0;
        vertical-align: text-bottom;
        margin-left: .125em;
    }
    & + figcaption {
        margin-left: 2em; 
    }
}
```

[An example of how this looks can be found on any of our quote posts](http://www.projectevolution.com/blurg/quotes/). 

The one drawback I have found is that this style pattern **requires** the contents of the blockquote to be enveloped by a `<p>` tag. Though the worst that happens is that the closing curly quote is not present.
